defaults: &defaults
  server: "mailserver_address" #change it to the real one
  template: "default_notification_template.txt"
  header:
    from: "s2-exception-notifier-noreply@sanger.ac.uk"
    from_alias: "S2 - Exception Notifier No Reply"
    to: "recipient@emailaddress.com" #change it to the real one
    subject: "[S2 Exception Notifier]"

test:
  <<: *defaults

development:
  <<: *defaults

production:
  <<: *defaults
