# This is just an example file.
# You have to move this file to your host application, which is using the
# Exception Notifier app.
# Please, move it to config folder with the following name: exception-email.yml.
# Please, change the value of the following items:
#  * server
#  * from
#  * to
# to make the application work.

server: "mail.sanger.ac.uk"  #change it to the real one
template: "default_notification_template.txt"
header:
  from: "s2-exception-notifier-noreply@sanger.ac.uk"
  from_alias: "S2 - Exception Notifier No Reply"
  to: "ke4@sanger.ac.uk"  #change it to the real one
  subject: "[S2 Exception Notifier]"
